name: dfl
channels:
- 1adrianb
- conda-forge
- anaconda
dependencies:
- python=3.6.8
- cudnn=7.6.5
- cudatoolkit=10.0.130
- pip:
  - tqdm
  - numpy==1.17.0
  - h5py==2.9.0
  - opencv-python==4.1.0.25
  - ffmpeg-python==0.1.17
  - scikit-image==0.14.2
  - scipy==1.4.1
  - colorama
  - labelme==4.2.9
  - tensorflow-gpu==1.13.2
